Rocho_app/__init__.py
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user, logout_user
from functools import wraps
app = Flask(__name__)

#app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
#app.config['SQLALCHEMY_DATABASE_URI']=
app.config.from_object('configuration.DevelopmentConfig')
app.config['DOWNLOAD_FOLDER'] = '../recetas'
descargas=app.config['DOWNLOAD_FOLDER']
db=SQLAlchemy(app)
login_manager = LoginManager()
login_manager.init_app(app)

login_manager.login_view = "fauth.login"
def administrador(f):
    @wraps(f)
    def wrapper(*args,**kwds):
        print(current_user.rol.value)
        if current_user.rol.value != "admin":
            logout_user()
            return redirect(url_for('fauth.login'))
            #login_manager.unauthorized()
            #return "Tu debes de ser Administrador",403
        return f(*args,**kwds)
    return wrapper
from Rocho_app.pacientes.paciente import pacientes
from Rocho_app.pacientes.categoria import expedientes
from Rocho_app.auth.views import auth
from Rocho_app.fauth.views import fauth

app.register_blueprint(pacientes)
app.register_blueprint(expedientes)
#app.register_blueprint(auth)
app.register_blueprint(fauth)

db.create_all()

Rocho_app/fauth/views.py
from flask import Blueprint,session,render_template, request,redirect, url_for, flash, get_flashed_messages, abort
from Rocho_app.auth.model.user import Usuario, LoginForm,RegisterForm
from Rocho_app import db
from Rocho_app import administrador
from flask_login import login_user, logout_user, current_user, login_required
from Rocho_app import login_manager
fauth = Blueprint('fauth',__name__)

@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(user_id)

@fauth.route('/registro',methods=['GET','POST'])
def registro():
    form = RegisterForm(meta={'csrf':False})
    if form.validate_on_submit():
        if Usuario.query.filter_by(username=form.username.data).first():
            flash("Ya existe este usuario en el sistema",'danger')
        else:
            p = Usuario(form.username.data,form.password.data) 
            db.session.add(p) #agregar un registro a la base de datos
            db.session.commit() #agregar instruccion para que se pueda subir a la base de datos 
            flash("Usuario creado con exito")
        return redirect(url_for('fauth.registro'))
    if form.errors:
        flash(form.errors,'danger')

    return render_template('auth/registro.html',form=form)


@fauth.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        flash("Ya estas autenticado")
        return redirect(url_for("expedientes.home"))
    form = LoginForm(meta={'csrf':False})
    
    if form.validate_on_submit():
        user = Usuario.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash("Bienvenido "+ user.username+" 😀")
            next = request.form['next'] 
            print(next)
            return redirect(next or url_for('expedientes.home'))
        else:
            flash("Ingreso su usuario y/o contraseña mal",'danger')
        return redirect(url_for('fauth.login'))
    if form.errors:
        flash(form.errors,'danger')

    return render_template('auth/login.html',form=form)
@fauth.route('/logout',methods=['GET','POST'])
def logout():
    logout_user()
    return redirect(url_for('fauth.login'))

@fauth.route("/protegido")
@login_required
def protegido():
    return "vista protegida"

Rocho_app/pacientes/__init__.py
#sin contenido
#necesario para crear una app modular en python

Rocho_app/templates/_form.html
<div class="form-row">
    <div class="form-group col-md-6">
        {{ form.nombre.label}}
        {{ form.nombre(class="form-control",id="inputNombre4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.apellidos.label}}
        {{ form.apellidos(class="form-control",id="inputApellidos4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.edad.label}}
        {{ form.edad(class="form-control",id="inputEdad4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.peso.label}}
        {{ form.peso(class="form-control",id="inputPeso4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.talla.label}}
        {{ form.talla(class="form-control",id="inputTalla4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.grupo_s.label}}
        {{ form.grupo_s(class="form-control",id="inputGrupo_s4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.temperatura.label}}
        {{ form.temperatura(class="form-control",id="inputTemperatura4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.fecha.label}}
        {{ form.fecha(class="form-control",id="inputFecha4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.sintomas.label}}
        {{ form.sintomas(class="form-control",id="inputSintomas4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.padecimientos.label}}
        {{ form.padecimientos(class="form-control",id="inputPadecimientos4")}}
    </div>
    <div class="form-group col-md-6">
        {{ form.alergias.label}}
        {{ form.alergias(class="form-control",id="inputAlergias4")}}
    </div>

<div class="form-group col-md-6">
    {{ form.tratamiento.label}}
    {{ form.tratamiento(class="form-control",id="inputTratamiento")}}
</div>
<div class="form-group col-md-6">
    {{ form.categoria_id.label}}
    {{ form.categoria_id(class="form-control")}}
</div>

</div>

Rocho_app/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='iconos/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='personalizado/css/style.css') }}">

    <title>Patli</title>
</head>
<body>
        {% include 'fragmentos/_nav.html' %}
    <div class="container">
        {% include 'fragmentos/_alert.html' %}
        {% block container %}
        {% endblock %}
    </div>
    
    {% include 'fragmentos/_footer.html' %}
    

    <script src="{{ url_for('static',filename='personalizado/script/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static',filename='personalizado/script/popper.min.js') }}"></script>
    <script src="{{ url_for('static',filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static',filename='personalizado/script/main.js') }}"></script>





</body>
</html>

Rocho_app/templates/categoria/_form.html
<div class="form-row">
    <div class="form-group col-md-6">
        {{ form.nombre.label}}
        {{ form.nombre(class="form-control",id="inputNombre4")}}
    </div>
</div>

Rocho_app/templates/categoria/crear.html
{% extends 'base/base.html' %}

{% block container %}
    <form action="{{ url_for('expedientes.crear') }}" method="POST">
        {%include 'categoria/_form.html'%}        

        <input type="submit" value="Crear" class="btn btn-secondary">
    </form>
    
{% endblock %}

Rocho_app/templates/categoria/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{producto['name']}}</h1>
    <ul>
        <li>{{producto['category']}}</li>
        <li>Filtro default: {{producto['price'] | default('sin precio',True)}}</li>
        <li>{{producto['category']}}</li>
    </ul>
</body>
</html>

Rocho_app/templates/categoria/index.html
{% extends 'base/base.html' %}
{% from 'macros/_paginacion_exp.html' import m_pagination %}
{% block container %}
    <h1>Expedientes: </h1>
    <a class="btn btn-primary btn-lg" href="{{ url_for('expedientes.crear')}}" role="button"><i class="fa fa-folder-open" data-toggle="tooltip" data-placement="top" title="Crear Expediente"></i></a>
    {%for categoria in expedientes.items%}
    <div class="card mb-3 form-small" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{url_for('static',filename='img/index.png')}}" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{categoria['nombre'] }} {{categoria['apellidos']}}</h5>
            <p class="card-text"><strong>Tratamiento:</strong> {{categoria['tratamiento']}}</p>
            <p class="card-text">
              <a class="btn btn-success btn-sm" href="{{ url_for('expedientes.update',id=categoria['id']) }}"><i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i></a> 
          <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-nombre="{{categoria['nombre']}}" data-id="{{categoria['id']}}" href=" "><i class="fa fa-folder-minus" data-toggle="tooltip" data-placement="top" title="Eliminar"></i></button>
            </p>
          </div>
        </div>
      </div>
    </div>
       
    {%endfor%}
    <div class="form-small">
      {{ m_pagination(expedientes) }}
    </div>
    
    <div class="modal fade " id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" >Eliminar: <span></span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Va a eliminar un expediente ¿está seguro de continuar?
          </div>
          <div class="modal-footer">
            
            <a href="#" id="deleteExpediente" class="btn btn-danger">Si</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          </div>
        </div>
      </div>
    </div>

    <script>
      window.onload=function(){
        $('#deleteModal').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) 
          var nombre = button.data('nombre')
          var id = button.data('id')
          var modal = $(this)
          modal.find('.modal-title span').text(nombre)
          $("#deleteExpediente").attr("href","/expediente-delete/"+id)
        })
    }
   
    </script>
{% endblock %}

Rocho_app/templates/categoria/paciente.html
{% extends 'base/base.html' %}

{% block container %}
    <h1>Paciente: {{paciente['nombre']}} {{paciente['apellido_paterno']}} {{paciente['apellido_materno']}}</h1>
    <h2>Edad: {{paciente['edad']}}</h2>
    <ul>
        <li>Sintomas: {{paciente['sintomas']}}</li>
        <li>Padecimientos: {{paciente['padecimientos']}}</li>
        <li>Alergias: {{paciente['alergias']}}</li>
        <li>Tratamiento: {{paciente['tratamiento']}}</li>
    </ul>
{% endblock %}
    

Rocho_app/templates/categoria/update.html
{% extends 'base/base.html' %}

{% block container %}
    <form action="{{ url_for('expedientes.update',id=categoria.id) }}" method="POST">
        {%include 'categoria/_form.html'%}        

        <input type="submit" value="Actualizar" class="btn btn-secondary">
    </form>
    
{% endblock %}

Rocho_app/templates/crear.html
{% extends 'base/base.html' %}

{% block container %}
    <form action="{{ url_for('pacientes.crear') }}" method="POST">
        {%include '_form.html'%}        

        <input type="submit" value="Crear" class="btn btn-secondary">
    </form>
    
{% endblock %}

Rocho_app/templates/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{producto['name']}}</h1>
    <ul>
        <li>{{producto['category']}}</li>
        <li>Filtro default: {{producto['price'] | default('sin precio',True)}}</li>
        <li>{{producto['category']}}</li>
    </ul>
</body>
</html>

Rocho_app/templates/fragmentos/_alert.html
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success fade show mt-3">{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

Rocho_app/templates/fragmentos/_footer.html
<footer class="navbar-dark bg-light">

  <div class="text-center py-3">© 2020 Copyright:
    <a href=""> patli</a>
  </div>

</footer>

Rocho_app/templates/fragmentos/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
    <a class="navbar-brand" href="#"><img src="{{url_for('static',filename='img/index.png')}}" alt="logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if current_user.username %}
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('expedientes.home')}}">Inicio</a>
          </li>
        
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Opciones
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('pacientes.home')}}">Paciente</a>
              <a class="dropdown-item" href="{{url_for('expedientes.home')}}">Expedientes</a>
             
            </div>
          </li>
        {% endif %}
        
       
      </ul>
      <ul class="navbar-nav ">
        {% if current_user.username %}
          
        {% else %}
       
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('fauth.login')}}">Iniciar sesión</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('fauth.registro')}}">Registrarse</a>     
          </li>
        {% endif %}
       
        
        {% if current_user.username %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hola: {{current_user.username}}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Perfil</a>
              <a class="dropdown-item" href="{{url_for('fauth.logout')}}">Logout</a>
              
             
            </div>
          </li>
        {% endif %}
        
         

       
      </ul>
    </div>
</nav>

Rocho_app/templates/index.html
{% extends 'base/base.html' %}
{% from 'macros/_paginacion.html' import m_pagination %}
{% block container %}
    <h1>Pacientes: </h1>
    <a class="btn btn-primary btn-lg" href="{{ url_for('pacientes.crear')}}" role="button"><i class="fa fa-user-injured" data-toggle="tooltip" data-placement="top" title="Nuevo Paciente"></i></a>
    {%for paciente in pacientes.items%}
    <div class="card mb-3 form-small" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{url_for('static',filename='img/index.png')}}" class="card-img" alt="...">
        </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{paciente['nombre'] }} {{paciente['apellidos']}}</h5>
        <p class="card-text">
          <strong>Expediente:</strong> {{ paciente['categoria'].nombre }}
          <br>
          <strong>Síntomas:</strong> {{paciente['sintomas']}}
          <br>
          <strong>Alergias:</strong>{{paciente['alergias']}}
          <br>
        </p>
        <p class="card-text">
          <a class="btn btn-primary btn-lg" href="{{ url_for('pacientes.receta',id=paciente['id'])}}" role="button"><i class="fa fa-book-reader" data-toggle="tooltip" data-placement="top" title="Ver más"></i></a>
          <hr class="my-4">
          <a class="btn btn-success btn-sm" href="{{ url_for('pacientes.update',id=paciente['id']) }}"><i class="fa fa-user-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i></a> 
          <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-nombre="{{paciente['nombre']}}" data-id="{{paciente['id']}}" href=" "><i class="fa fa-user-minus" data-toggle="tooltip" data-placement="top" title="Eliminar"></i></button> 
        </p>
      </div>
    </div>
  </div>
</div>
     
    {%endfor%}
    <div class="form-small">
      {{ m_pagination(pacientes) }}
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" >Eliminar: <span></span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Va a eliminar un paciente ¿está seguro de continuar?
          </div>
          <div class="modal-footer">
            
            <a href="#" id="deletePaciente" class="btn btn-danger">Si</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          </div>
        </div>
      </div>
    </div>
    <script>
      window.onload=function(){
        $('#deleteModal').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) // Button that triggered the modal
          var nombre = button.data('nombre')
          var id = button.data('id')
          var modal = $(this)
          modal.find('.modal-title span').text(nombre)
          $("#deletePaciente").attr("href","/paciente-delete/"+id)
        })
    }
    </script>
{% endblock %}

Rocho_app/templates/macros/_paginacion.html
{% macro m_pagination(pagination)%}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pagination.has_prev%}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('pacientes.home', page=pagination.prev_num) }}"><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% endif %}
            {%- for page in pagination.iter_pages() %}
                
                    {% if page != pagination.page %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('pacientes.home', page=page) }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page }}</a>
                        </li>
                    <strong></strong>
                    {% endif %}
            {%- endfor %}
            {% if pagination.has_next%}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('pacientes.home', page=pagination.next_num) }}"><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% endif %}
        </ul>
    </nav>
{%- endmacro%}

      
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      
    </ul>
  </nav>

Rocho_app/templates/macros/_paginacion_exp.html
{% macro m_pagination(pagination)%}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pagination.has_prev%}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('expedientes.home', page=pagination.prev_num) }}"><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% endif %}
            {%- for page in pagination.iter_pages() %}
                
                    {% if page != pagination.page %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('expedientes.home', page=page) }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page }}</a>
                        </li>
                    <strong></strong>
                    {% endif %}
            {%- endfor %}
            {% if pagination.has_next%}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('expedientes.home', page=pagination.next_num) }}"><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% endif %}
        </ul>
    </nav>
{%- endmacro%}

      
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      
    </ul>
  </nav>

Rocho_app/templates/paciente.html
{% extends 'base/base.html' %}

{% block container %}
<div class="card">
    <h5 class="card-header">Receta</h5>
    <div class="card-body">
      <h5 class="card-title">{{paciente['nombre']}} {{paciente['apellidos']}}</h5>
      <form action="{{ url_for('pacientes.receta',id=paciente.id) }}" method="POST">
        {%include '_form.html'%}        
        
        <input type="submit" value="Crear Receta" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Paso 1">
        <a class="btn btn-secondary" href="/descargar/{{(paciente['nombre']+'.docx')}}"><i class="fa fa-file-download" data-toggle="tooltip" data-placement="top" title="Paso 2"></i></a> 
        </form>
      
    </div>
  </div>
  
{% endblock %}
    

Rocho_app/templates/update.html
{% extends 'base/base.html' %}

{% block container %}
    <form action="{{ url_for('pacientes.update',id=paciente.id) }}" method="POST">
        {%include '_form.html'%}        

        <input type="submit" value="Actualizar" class="btn btn-secondary">
    </form>
    
{% endblock %}